version: '3'
services:
  node:
    container_name: sky_app
    restart: always
    build: .
    depends_on:
      - mongo
    ports:
      - 3001:3001
    volumes:
      - ./:/code
  mongo:
    container_name: sky_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: